# Generated by Django 2.2.12 on 2020-04-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NEJM', 'New England Journal of Medicine'), ('JVS', 'Journal of Vascular Surgery')], max_length=256)),
                ('renewal_date', models.DateField(verbose_name='Date of Renewal')),
                ('cme_available', models.DateField(verbose_name='CME Available')),
                ('sub_cost', models.FloatField(blank=True, max_length=6)),
                ('icon_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('credit_for', models.CharField(choices=[('ABS', 'American Board of Surgery'), ('ABMS', 'American Board of Medical Specialties')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ACS', 'American College of Surgeons'), ('AMA', 'American Medical Association')], max_length=256)),
                ('renewal_date', models.DateField(verbose_name='Date of Renewal')),
                ('cme_available', models.DateField(verbose_name='CME Available')),
                ('sub_cost', models.FloatField(blank=True, max_length=6, null=True)),
                ('icon_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('credit_for', models.CharField(choices=[('ABS', 'American Board of Surgery'), ('ABMS', 'American Board of Medical Specialties')], max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
