# Generated by Django 2.2.12 on 2020-04-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0004_auto_20200429_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='credit_for',
            field=models.CharField(choices=[('', 'American Board of Surgery'), ('', 'American Board of Medical Specialties')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='name',
            field=models.CharField(choices=[('', 'New England Journal of Medicine'), ('', 'Journal of Vascular Surgery')], max_length=256),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='sub_cost',
            field=models.FloatField(blank=True, max_length=6, verbose_name='Subscription Cost'),
        ),
        migrations.AlterField(
            model_name='membershipentry',
            name='credit_for',
            field=models.CharField(choices=[('', 'American Board of Surgery'), ('', 'American Board of Medical Specialties')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='membershipentry',
            name='name',
            field=models.CharField(choices=[('', 'American College of Surgeons'), ('', 'American Medical Association')], max_length=256),
        ),
        migrations.AlterField(
            model_name='membershipentry',
            name='sub_cost',
            field=models.FloatField(blank=True, max_length=6, null=True, verbose_name='Subscription Cost'),
        ),
    ]
