# Generated by Django 3.0.8 on 2020-08-28 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subs', '0009_auto_20200806_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, null=True)),
                ('cycle_1_length', models.IntegerField(null=True)),
                ('cycle_1_total_cme_req', models.IntegerField(null=True)),
                ('cycle_1_cat_1_req', models.IntegerField(null=True)),
                ('cycle_1_self_req', models.IntegerField(null=True)),
                ('cycle_2_length', models.IntegerField(null=True)),
                ('cycle_2_total_cme_req', models.IntegerField(null=True)),
                ('cycle_2_cat_1_req', models.IntegerField(null=True)),
                ('cycle_2_self_req', models.IntegerField(null=True)),
                ('cycle_2_cat_2_req', models.IntegerField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='boardentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='boardentry',
            name='timeline',
        ),
        migrations.AlterField(
            model_name='boardentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardentry',
            name='entry',
            field=models.ManyToManyField(null=True, related_name='users', to='subs.Board'),
        ),
    ]
