# Generated by Django 3.0.8 on 2020-08-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0010_auto_20200828_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardentry',
            name='entry',
            field=models.ManyToManyField(related_name='users', to='subs.Board'),
        ),
    ]
