# Generated by Django 2.2.12 on 2020-08-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0011_auto_20200828_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardentry',
            old_name='entry',
            new_name='board',
        ),
    ]
