# Generated by Django 2.2.12 on 2020-08-28 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0012_auto_20200828_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardentry',
            name='board',
        ),
        migrations.AddField(
            model_name='boardentry',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='subs.Board'),
        ),
    ]
