# Generated by Django 2.2.12 on 2020-08-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0013_auto_20200828_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cycle_1_cat_2_req',
            field=models.IntegerField(null=True),
        ),
    ]
