# Generated by Django 3.0.8 on 2020-08-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0014_board_cycle_1_cat_2_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardentry',
            name='first_reg',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='boardentry',
            name='last_reg',
            field=models.DateField(null=True),
        ),
    ]
