# Generated by Django 2.2.12 on 2020-08-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0015_auto_20200828_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardentry',
            name='timeline_tag',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
