# Generated by Django 2.2.12 on 2020-08-29 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subs', '0016_boardentry_timeline_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, null=True)),
                ('cycle_length', models.IntegerField(null=True)),
                ('cycle_total_cme_req', models.IntegerField(null=True)),
                ('cycle_cat_1_req', models.IntegerField(null=True)),
                ('cycle_self_req', models.IntegerField(null=True)),
                ('cycle_cat_2_req', models.IntegerField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_reg', models.DateField(null=True)),
                ('last_reg', models.DateField(null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='subs.State')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
