# Generated by Django 3.0.8 on 2020-08-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0017_state_stateentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='cycle_self_req',
        ),
    ]
